### ISSUE TITLE
Add Support for Multiple Languages in Text-to-Speech Feature

### ISSUE THREAD

**Issue by selmankocael** [Rics-Dev/uRead#1]
Feature Request:
The current text-to-speech (TTS) feature in the book reading application only supports English. To enhance the reading experience for users of different languages, it would be beneficial to add an option for selecting the TTS language.

Requirements:

Allow users to choose the TTS language through book settings or app preferences.
Integrate support for additional languages (e.g., Turkish, German, French).
Utilize appropriate TTS engines for the selected language.
Why is this needed?
This feature will improve the reading experience for multilingual users and increase the application's accessibility and global appeal.

**Comment by Rics-Dev** [comment]
Done in version 1.1.0,  Added support for languages in both app Translation and Text-To-Speech
